version: "3"
services:
############################ HDFS #################################
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop2.7.4-java8
    container_name: namenode
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop.env
    ports:
      - 8020:8020
      - 50070:50070
  datanode-1:
    image: bde2020/hadoop-datanode:2.0.0-hadoop2.7.4-java8
    container_name: datanode-1
    environment:
      SERVICE_PRECONDITION: "namenode:50070"
    env_file:
      - ./hadoop.env
    ports:
      - 50075:50075

  datanode-2:
    image: bde2020/hadoop-datanode:2.0.0-hadoop2.7.4-java8
    container_name: datanode-2
    environment:
      SERVICE_PRECONDITION: "namenode:50070"
    env_file:
      - ./hadoop.env
    ports:
      - 50076:50075

############################# SPARK ############################
  spark-master:
    image: spark-master:latest
    container_name: spark-master
    ports:
      - "8083:8080"
      - "7078:7077"
    environment:
      - INIT_DAEMON_STEP=setup_spark
    volumes:
      - $PWD/../shared:/data
  spark-worker-1:
    image: spark-worker:latest
    container_name: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - "38081:8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"

  spark-worker-2:
    image: spark-worker:latest
    container_name: spark-worker-2
    depends_on:
      - spark-master
    ports:
      - "48081:8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
      
      
# ######################### Kafka ###############

#   zookeeper:
#     image: wurstmeister/zookeeper
#     container_name: zookeeper
#     expose:
#       - "2181"
#     ports:
#       - 2181:2181
           
#   kafka:
#     image: wurstmeister/kafka
#     container_name: kafka
#     expose:
#       - "9092"
#     ports:
#       - 9092:9092
#     environment:
#       KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#       KAFKA_ADVERTISED_PORT: 9092
#       KAFKA_ADVERTISED_HOST_NAME: kafka
#       KAFKA_ADVERTISED_LISTENERS: INSIDE://:9092,OUTSIDE://localhost:19092
#       KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://0.0.0.0:19092
#       KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
#       KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      

#   kafka_manager:
#     image: hlebalbau/kafka-manager:1.3.3.18
#     container_name: kafka_manager
#     expose:
#       - "9000"
#     ports:
#       - 9000:9000
#     environment:
#       ZK_HOSTS: "zookeeper:2181"
#       APPLICATION_SECRET: "random-secret"
#       command: -Dpidfile.path=/dev/null
#     links:
#         - kafka
#         - zookeeper
#     depends_on:
#         - "zookeeper"
#         - "kafka"
      
           
######################### notebook ############
  dashboard-notebook:
    image: dashboard:latest
    container_name: dashboard-notebook
    ports:
      - "8888:8888"
    volumes:
      - $PWD/src:/home/jovyan/work
    environment:
      - JUPYTER_TOKEN=hoang

    
networks:
  default:
    external:
      name: hoang
